apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9deploy
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: web  # Pod 작성시 이 부분(label -> app: web)이 포함되어야 한다
  template: # 여기에서부터 Pod 작성
    metadata:
      labels:
        app: web # 반드시 (1) 과 동일해야 함
    spec:
      containers:
        - name: aws9ctn
          image: kosunjo/aws9:green
---

apiVersion: v1
kind: Service
metadata:
  name: aws9-svc
spec:
  type: NodePort
  ports:
  - name: aws9-port
    port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: web